### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by Gliscor** [angeloanan/MPC-DiscordRPC#11]
Followed all the installation steps but doesn't show what i'm listening/viewing on discord.

**Comment by angeloanan** [comment]
Does it still not work? Can you include some logs here?

**Comment by Ianuela** [comment]
I'm having the same issue
It'll work for a few days then just stop all of a sudden
I redownloaded Discord and that seemed to fix it for a while but now it's back to not showing anything @angeloanan

**Comment by liddack** [comment]
@Ianuela @Gliscor There's a file called `mpc-discordrpc.log` in your MPC-DiscordRPC folder. Could you please paste it here so we can better understand what's the issue?

**Comment by Ianuela** [comment]
[mpc-discordrpc.log](https://github.com/angeloanan/MPC-DiscordRPC/files/3992061/mpc-discordrpc.log)
@liddack @angeloanan Hope this is the right one friendos

**Comment by Ianuela** [comment]
So any updates fellas?

**Comment by liddack** [comment]
Sorry for being inactive for so long 😓
I need more info on this. Is your profile always showing the "idling" status or the MPC presence is not being displayed at all? 
In case of the latter, make sure either Discord app, MPC, or CMD are not running on elevated (administrator) mode, as they're all meant to be run in normal mode. Also make sure the port set in `config.js` is the same one set in your `Web Interface` setting in MPC-HC options. Check your firewall settings as well, as there's a chance it will block either the `13579` port or MPC-HC itself. If needed, try to change the port number on both settings - try 3000, 5000, 8000, or anything above 1023.

To test it out, open both Discord and MPC, open a CMD window, navigate to MPC-DiscordRPC folder and run 

```
npm stop
node index.js
``` 
The log's contents will now be shown in your CMD window. Check if it's working - it should log something like: 

```
INFO: Loading...
INFO: Fully ready. Trying to connect to Discord client...
INFO: Connected to Discord. Listening MPC on http://localhost:13579/variables.html
INFO: Connected to MPC-HC WebServer
INFO: Presence update sent: Playing - 00:00 / 00:51 - video.mp4
```

If you got an error, post it along with the full path of the file used in the test.

**Comment by Ianuela** [comment]
I threw that into Command Prompt and I got 

C:\Users\Ianuela>npm stop
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\Ianuela\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Ianuela\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ianuela\AppData\Roaming\npm-cache\_logs\2020-02-14T23_58_01_947Z-debug.log

C:\Users\Ianuela>node index.js
internal/modules/cjs/loader.js:957
    throw err;
    ^

Error: Cannot find module 'C:\Users\Ianuela\index.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:954:17)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:847:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:67:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}

As for the file tested, 
C:\Users\Ianuela>"C:\Users\Ianuela\Desktop\Animu\Pokemon\Pokemon Diamond & Pearl\[RAW] Pokemon Diamond & Pearl [480p,1080p]\[RAW] Pokemon Diamond & Pearl - 153 [1080p].mkv"

I'm not sure I posted exactly what you wanted but I'm a brainlet when it comes to technology so please don't bully uwu

**Comment by liddack** [comment]
@Ianuela you did almost everything right - you only need first to open a command prompt window in the folder where you extracted the MPC-DiscordRPC files. A simple way to do so is navigating to that folder with Windows Explorer, typing `cmd` into the address bar and pressing <kbd>Enter</kbd>.

![example](https://i.snipboard.io/l5Wyzx.jpg)

Now you can run the commands I mentioned. If the second command display the output mentioned in my last comment and the presence in your Discord profile works properly, the test passed. But if you close the command prompt window right after, the presence will stop working. To get it working in the background, press <kbd>Ctrl</kbd> + <kbd>C</kbd> to stop the `node index` command and then run `npm start`. Then you can close your CMD window :)

> PS: If you still get the `Error: Cannot find module...`, run `npm install` (this error means the necessary dependencies are not installed) and then try to run those commands again.

**Comment by Ianuela** [comment]
It seems to be working! Thanks for walking me through this and I'll update if it ever stops again. Thanks again for all the help!

**Comment by Ianuela** [comment]
Hello there again my good friend @liddack ! Hope you're doing well amidst these trying times!
The program's been running kind of on and off ever since we last spoke, and usually I just poke it with an "npm start" and it starts working again. This time, however, I can't seem to get it back up. Could you help me out here? Thanks in advance. PS here's what happens when I do the "node index.js" thing you were talking about before:
C:\Users\Ianuela\Downloads\MPC-DiscordRPC-master>node index.js
[23:55:55] INFO: Loading...
[23:55:56] INFO: Fully ready. Trying to connect to Discord client...
[23:56:06] WARN: Connection to Discord has failed. Trying again in 10 seconds...

**Comment by liddack** [comment]
Hello, I hope you're doing well too :)
From the log you provided, I see the program is having a hard time trying to connect to your Discord client. I just tested the program and it seems to be working well, and I haven't change the code in the last few months. Please try doing the following:
- Close all Node.js processes and run "node index.js" to see if it works. To do so, open Task Manager, open the Details tab, find all processes named "node.exe" and click "End Task" for each one.
If it still doesn't...
- Test if another Rich Presence app is working for you. Here is the link for [Discord Rich Presence Tool](https://github.com/Rarcoon/Discord-Rich-Presence-Tool/releases/download/v1.0.2/drpt_1_0_2_win64.zip). Just type anything in the "Game/activity name" field and click "Update", then check if it gets displayed on your profile.

**Comment by Ianuela** [comment]
How curious! I ended two instances of programs with "node" in their names and it seems to be working again. Man, I don't understand computers at all. Thanks for all your help man! I kinda feel bad having you walk me through this but at the same time I love flexing my great taste in anime to all my Discord friends lol

**Comment by GenesisAria** [comment]
I ran into it doing the same thing, but nothing of the above works... Running it like normal (npm start) it starts, but not sending any data, the log is full of `WARN: Connection to Discord has failed. Trying again in 10 seconds...`  Other rich presence work just fine.  I'd tried running repairs, updating node, amongst other things, to no avail.  Checked router as well.
