### ISSUE TITLE
Run on startup

### ISSUE THREAD

**Issue by TrulyZ** [angeloanan/MPC-DiscordRPC#12]
This is not an issue so I know this isn't the right place but I didn't know where else to ask.

I'm not very good at this kind of stuff so I'd really appreciate it if anyone could tell me how I could have this always be on.
Other than that it's been working very well for me, good job and thanks!

**Comment by liddack** [comment]
Glad to hear that! 
You can use Windows **Task Scheduler** to do so.

1. Open start menu, search for **Task Scheduler** and open it
1. On the **Actions** menu, click **Create Basic Task**
1. Type a name for the task and an optional description, and then click **Next**
1. Select **When I log on** and click **Next**
1. Select **Start a program** and then click **Next**
1. In the following fields, type:
 - Program/script: **npm**
 - Add arguments: **start**
 - Start in: [Your MPC-DiscordRPC folder location]
![image](https://user-images.githubusercontent.com/8820502/68076675-8e8c6c80-fd96-11e9-8b19-3e1a9fd0ba32.png)
 - Click **Next**
1. Click **Finish**

From now on, every time you log on to your account a CMD window launching MPC-DiscordRPC will briefly show up. To hide that window, please [follow these instructions](https://pureinfotech.com/prevent-command-window-appearing-scheduled-tasks-windows-10/).

If you want it to stop launching on startup, open your Task Scheduler, right-click the task you created and then click **Disable**.

Let me know if this worked out for you!

**Comment by TrulyZ** [comment]
That did exactly what I wanted! Thank you so much for taking your time and making it so simple!
