### ISSUE TITLE
Need to remove dots in addition to underscores

### ISSUE THREAD

**Issue by shihofuyu** [angeloanan/MPC-DiscordRPC#13]
Works great but I think in addition to offering the option to remove underscores, it would also make a lot of sense to remove dots too, since your regular video release file isn't named "Your_Favorite_Movie.mkv" but rather "Your.Favorite.Movie.mkv"

Could this please be added?

**Comment by liddack** [comment]
Just added the [`exports.replaceDots`](https://github.com/angeloanan/MPC-DiscordRPC#exportsreplacedots) option.

Follow the [update instructions](https://github.com/angeloanan/MPC-DiscordRPC#how-to-update) and let me know if it worked out for you!

**Comment by shihofuyu** [comment]
Awesome, thank you! Works like a charm.
