### ISSUE TITLE
Not work after Node.js v17

### ISSUE THREAD

**Issue by gspbeetle** [angeloanan/MPC-DiscordRPC#24]
Not a bug, but it seems that Node.js v17 can break MPC-DiscordRPC for reason unknown. Might want to stick with v16.xx

**Comment by liddack** [comment]
Thanks for reporting this issue!

I was able to solve the connection error on v17.x with a simple fix which is included in the [new version I just released](https://github.com/angeloanan/MPC-DiscordRPC/releases/tag/v0.5.0).
Give it a try when you can and let me know if it is working as expected.

**Comment by gspbeetle** [comment]
Thanks for the fix, working now. Its snekfetch.
